name: Daily AI Post

on:
  schedule:
    - cron: '0 14 * * *'  # every day at 10am EST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create AI Post
      run: |
        mkdir -p _posts
        echo "---" > _posts/$(date +'%Y-%m-%d')-post.md
        echo "title: "AI Musings $(date +'%Y-%m-%d')"" >> _posts/$(date +'%Y-%m-%d')-post.md
        echo "layout: post" >> _posts/$(date +'%Y-%m-%d')-post.md
        echo "---" >> _posts/$(date +'%Y-%m-%d')-post.md
        echo "Today’s thought: $(curl https://api.quotable.io/random | jq -r '.content')" >> _posts/$(date +'%Y-%m-%d')-post.md

    - name: Commit post
      run: |
        git config user.name "theaibloggerbot"
        git config user.email "bot@aiblogger.com"
        git add _posts
        git commit -m "chore: daily post"
        git push
