name: Daily AI Hugo Post (ChatGPT)

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  generate_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai==0.28

      - name: Generate Hugo post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p content/posts
          DATE=$(date +'%Y-%m-%d')
          FILENAME="content/posts/${DATE}-chatgpt.md"
          echo "+++" > $FILENAME
          echo "title = \"ChatGPT Reflections - $DATE\"" >> $FILENAME
          echo "date = \"$DATE\"" >> $FILENAME
          echo "draft = false" >> $FILENAME
          echo "+++" >> $FILENAME
          echo "" >> $FILENAME
          echo "import openai" > generate.py
          echo "openai.api_key = \"$OPENAI_API_KEY\"" >> generate.py
          echo "response = openai.ChatCompletion.create(" >> generate.py
          echo "  model='gpt-4'," >> generate.py
          echo "  messages=[" >> generate.py
          echo "    {'role': 'system', 'content': 'You are a thoughtful blogger who writes reflective, long-form content on self-improvement, motivation, and mindful living.'}," >> generate.py
          echo "    {'role': 'user', 'content': 'Write a 700-1000 word blog post with a meaningful, insightful tone. Include a title.'}" >> generate.py
          echo "  ]" >> generate.py
          echo ")" >> generate.py
          echo "text = response['choices'][0]['message']['content']" >> generate.py
          echo "with open('$FILENAME', 'a', encoding='utf-8') as f: f.write(text.strip())" >> generate.py
          python3 generate.py

      - name: Commit and push
        run: |
          git config user.name "theaibloggerbot"
          git config user.email "bot@aiblogger.com"
          git add content/posts
          git commit -m "chore: daily Hugo post"
          git push
